### ISSUE TITLE
Can we use external css link

### ISSUE THREAD

**Issue by desilvaNSP** [artf/grapesjs-preset-newsletter#1]
I use this plugin with grapesjs.but I cannot external css link when importing html content.Inline css is working but external link such as bootstrap is not working.

**Comment by artf** [comment]
@desilvaNSP can you show me how are trying to include bootstrap? I can import bootstrap even from the demo:
Here I paste the code without bootstrap:
![no-boots](https://cloud.githubusercontent.com/assets/11614725/21781176/acd7f5e0-d6ae-11e6-8685-e0fa9ee8c400.jpg)

Here I add the bootstrap CDN resource at the end:
![with-boots](https://cloud.githubusercontent.com/assets/11614725/21781214/d0c60154-d6ae-11e6-8049-8ae553bb1775.jpg)

![mobile-boots](https://cloud.githubusercontent.com/assets/11614725/21781255/f4f26cca-d6ae-11e6-8c24-82c580004c20.png)

Here I explain what API to use for the import https://github.com/artf/grapesjs/issues/27

**Comment by desilvaNSP** [comment]
Thank you @artf..this is great puligin that you are created..cheers...!!!
