### ISSUE TITLE
gjs-get-inlined-html fails to update

### ISSUE THREAD

**Issue by rafal-olszewski** [artf/grapesjs-preset-newsletter#13]
The issue is that `gjs-get-inlined-html` command fails to update the hidden input to save the email template, it shows still "old" code despite the changes I've made to the template via editor.

Below you'll find a piece of the code that I'm using to save the templates in a modal provided by this editor.

```javascript
  cmd.add('save-template', {
    run(editor, sender) {
      sender.set('active', 0);
      const modalContent = modal.getContentEl();
      const mdlDialog = document.querySelector('.gjs-mdl-dialog');

      // wyciaga zle tutaj
      const cmdGetCode = cmd.get('gjs-get-inlined-html');
      contentEl.value = cmdGetCode.run(editor);
      console.log(contentEl.value)
      if (qs('id')) {
        $.get(`/${ue.currentAppKey}/emails/api/template/${qs('id')}/`, (res) => {
          templateName.value = res.name;
          templateDesc.value = res.description;
        });
      }
      mdlDialog.className += ` ${mdlClass}`;
      saveTemplate.style.display = 'block';
      modal.setTitle(gettext('Save template'));
      modal.setContent('');
      modal.setContent(saveTemplate);
      modal.open();
      modal.getModel().once('change:open', () => {
        mdlDialog.className = mdlDialog.className.replace(mdlClass, '');
        // clean status
      });
    },
  });
```

My best shot is that it fails on this piece of code

```js
contentEl.value = cmdGetCode.run(editor);
```

It supposed to update the hidden input in my form, but the code is still with old values, so whenever I'll save the template, it will be the old one.

**Comment by artf** [comment]
Just by using the demo I don't see any issue, try to run `editor.runCommand('gjs-get-inlined-html')` in your console (make the `editor` globally available first) and see if the content in output actually changes

**Comment by rafal-olszewski** [comment]
Will do, and I'll return if anything pops-up
