### ISSUE TITLE
Grapes skin overridden

### ISSUE THREAD

**Issue by santiph** [artf/grapesjs-preset-newsletter#15]
When using both GrapesJs and grapesjs-preset-newsletter styles, `$mainColor` set in grapes' variables is being overridden

https://github.com/artf/grapesjs-preset-newsletter/blob/master/src/style/main.scss#L72 
I've created https://github.com/artf/grapesjs-preset-newsletter/pull/14 to fix it

**Comment by artf** [comment]
Merged

**Comment by santiph** [comment]
Thanks @artf for your quick review! ;)
unfortunately, I'm unable to get this version from npm.
`npm i grapesjs-preset-newsletter` keeps installing an old version of the app. 
Also NPM says
```
artf artf published 5 months ago
0.2.3 is the latest of 4 releases
```
Could you please publish a new version with the latests updates?

**Comment by artf** [comment]
Published a new release 👍
