### ISSUE TITLE
Store the html and inline css in Editor.Store()

### ISSUE THREAD

**Issue by mekamleshk** [artf/grapesjs-preset-newsletter#16]
I am trying to store the html and inline css , can you please in how to pass it to editor.store() function.
@artf

```js
editor.Commands.add`
        ('save-db',
        {
            run: function(editor, sender)
            {
              sender && sender.set('active'); // turn off the button
              var html = editor.runCommand('gjs-get-inlined-html');
              editor.store();
              alert('Draft');
              console.log(html);

              editor.on('storage:store', function(e) {
                    console.log('Stored ', e);
              });         
            }
        });
```

Please recheck my code. @sonnylloyd  @artf 
I want to store inline html

`var html = editor.runCommand('gjs-get-inlined-html');`

into mysql database using
`editor.store()` function

**Comment by artf** [comment]
You can't do it with `editor.store()` try to call directly `editor.StorageManager.store({data: 'value'})`
