### ISSUE TITLE
Save Template Code in Database

### ISSUE THREAD

**Issue by Yppaws** [artf/grapesjs-preset-newsletter#18]
I need to save created templates in database.

Can anyone atleast tell me how to call html code so i can save?

**Comment by artf** [comment]
First of all, you're posting to a wrong repository, use this https://github.com/artf/grapesjs for a more general use and searching in [issues](https://github.com/artf/grapesjs/issues)/[wiki](https://github.com/artf/grapesjs/wiki) you should find your answer
