### ISSUE TITLE
how to store html and inline css

### ISSUE THREAD

**Issue by suraj740** [artf/grapesjs-preset-newsletter#19]
i want to store html and inline css in some variable, how can i do it in newsletter
and one more thing how can i align image to center, its not working.
Thanks @artf 
Please help me for solving this issue @artf 
![default](https://user-images.githubusercontent.com/24958883/31850847-c6152830-b677-11e7-8b2e-fb35428a56d0.png)

**Comment by artf** [comment]
You have the list of commands here https://github.com/artf/grapesjs-preset-newsletter#summary

**Comment by suraj740** [comment]
Thanks @artf 
But its not working, i had already tried this.
var commands = editor.Commands;
        commands.add('getHtmlBtn', {
            run: function (editor, sender) {
                // sender && sender.set('active'); // turn off the button
                sender.set('active', false);
                var html = editor.runCommand('gjs-get-inlined-html');
                editor.store();
                window.alert('Draft');
                console.log('html', html);
                editor.on('storage:store', function (e) {
                    console.log('Stored ', e);
                });
            }
        });
        var myCommand = commands.get('getHtmlBtn');
        myCommand.run();

**Comment by artf** [comment]
You should not call the command like this
```js
var myCommand = commands.get('getHtmlBtn');
myCommand.run();
```
just
```js
editor.runCommand('getHtmlBtn');
```

**Comment by suraj740** [comment]
Tried these commands , but same issue. 
var commands = editor.Commands;
        commands.add('getHtmlBtn', {
            run: function (editor, sender) {
                // sender && sender.set('active'); // turn off the button
                sender.set('active', false);
                var html = editor.runCommand('gjs-get-inlined-html');
                editor.store();
                window.alert('Draft');
                console.log('html', html);
                editor.on('storage:store', function (e) {
                    console.log('Stored ', e);
                });
            }
        });
        editor.runCommand('getHtmlBtn');
![screen shot 2017-10-23 at 6 48 55 pm](https://user-images.githubusercontent.com/24958883/31891073-e589e0f0-b822-11e7-9ccc-aa5c28e62e0e.png)

**Comment by artf** [comment]
check the console, you probably getting an error here `sender.set('active', false);`, remove it or put back the check you've commented `sender && sender.set('active')`

**Comment by suraj740** [comment]
Thanks @artf 
But getting same error using sender && sender.set('active');
 var commands = editor.Commands;
        commands.add('getHtmlBtn', {
            run: function (editor, sender) {
                sender && sender.set('active'); // turn off the button
                // sender.set('active', false);
                var html = editor.runCommand('gjs-get-inlined-html');
                editor.store();
                $window.alert('Draft');
                $log.debug('html', html);
                editor.on('storage:store', function (e) {
                    $log.debug('Stored ', e);
                });
            }
        });
        editor.runCommand('getHtmlBtn');
![screen shot 2017-10-25 at 5 42 21 pm](https://user-images.githubusercontent.com/24958883/31998039-eb5f6a42-b9ab-11e7-973a-74b5699f997f.png)

**Comment by artf** [comment]
@suraj740 `sender && sender.set && sender.set('active', false)`

**Comment by suraj740** [comment]
Thanks @artf 
Not getting error now , but button is also not visible to get html.
![screen shot 2017-10-25 at 6 14 27 pm](https://user-images.githubusercontent.com/24958883/31999326-8283d67a-b9b0-11e7-9f65-d1f1d90e2378.png)

**Comment by artf** [comment]
in your code, you didn't create any button...

**Comment by suraj740** [comment]
@artf , code is working and now i am able to store html and css.
Thank you very much.
