### ISSUE TITLE
Re-order of the panels button.

### ISSUE THREAD

**Issue by besingamkb** [artf/grapesjs-preset-newsletter#24]
Hi,. I use this grapesjs-present-newsletter preset. Is there a possible to organize its panels button possition?

Just like i want to merge the undo and redo button on the other buttons on the right side.?

**Comment by artf** [comment]
Hi Mark,
you can make use of [Panels API](https://github.com/artf/grapesjs/wiki/API-Panels) or yet simpler, being flex children, you can use CSS `order` property

**Comment by lechuhuuha** [comment]
> 

the link Panels api is no longer exists? Can you update its?
