### ISSUE TITLE
Better way to create images links

### ISSUE THREAD

**Issue by SwithFr** [artf/grapesjs-preset-newsletter#26]
Hi, 

New question, can you add a better way to create an image link? For now, you need to add a link block and drag and drop an image in it and then click on the img element, click on the top arrow to return to the link block to update the link attributes... That's not user firendly. Maybe you can use the rich text editor to make it easier?

Thank you

**Comment by artf** [comment]
Hi Jeremy, I close the issue as If I'm not mistaken you already find a way to accomplish this with a custom component https://github.com/artf/grapesjs/issues/665
