### ISSUE TITLE
Where's the newsletter CSS CDN?

### ISSUE THREAD

**Issue by CaptainHypertext** [artf/grapesjs-preset-newsletter#27]
In your usage example for the newsletter plugin, you show:
```
<link href="path/to/grapes.min.css" rel="stylesheet"/>
<link href="path/to/grapesjs-preset-newsletter.css" rel="stylesheet"/>
```

But you only have one CDN link for the js:
```
https://unpkg.com/grapesjs-preset-newsletter
```

So there isn't a CDN for `grapesjs-preset-newsletter.css`? Or do I just not understand how unpkg works?

**Comment by artf** [comment]
With unpkg  you can explore the content of the npm's package, so you can use this https://unpkg.com/grapesjs-preset-newsletter/dist/grapesjs-preset-newsletter.css
