### ISSUE TITLE
How does one build a newsletter from scratch?

### ISSUE THREAD

**Issue by CaptainHypertext** [artf/grapesjs-preset-newsletter#28]
I'm trying to implement this for non-technical end users to make their own email newsletters, but I don't get how to make something that looks like the demo.  How does the container and width get set up?  Am I supposed to initialize this with some kind of boilerplate template?  How is this supposed to work?

Also, the newsletter mentions testing with PutsMail?  Is that an option I can enable?

Thanks for any assistance.

**Comment by artf** [comment]
>How does the container and width get set up? Am I supposed to initialize this with some kind of boilerplate template?

Well, it's up to you here... you can init the editor with some kind of template or, for example, create a block which should be dropped on canvas

> Also, the newsletter mentions testing with PutsMail? Is that an option I can enable?

PutsMail was removed https://github.com/artf/grapesjs/issues/140
