### ISSUE TITLE
Icon for block

### ISSUE THREAD

**Issue by goldengrisha** [artf/grapesjs-preset-newsletter#29]
When I create block, I want to have an ability to add an Icon for my block :
```
blockManager.add('page-id', {
      category: 'Basic',
      label: 'Page',
      content: '<section class="bdg-sect"></section>',
       attributes: {
              class: 'gjs-fonts gjs-custom-field'
        } 
});
 
```

**Comment by artf** [comment]
@goldengrisha you can put any HTML string inside `label` (eg. like an [svg](https://github.com/artf/grapesjs-lory-slider/blob/master/src/blocks.js#L9-L13))
