### ISSUE TITLE
MJML support

### ISSUE THREAD

**Issue by HLFH** [artf/grapesjs-preset-newsletter#3]
Hi,

Can you support MJML?
https://github.com/mjmlio/mjml

It seems that you do not support HTML templates generated by MJML. 
I can't save my HTML templates generated by MJML.

Thanks,

**Comment by artf** [comment]
Really cool, seems like MJML takes care of a lot of stuff that I, probably, will never find time to integrate (eg. conditional tags). I'll definitely take a look

**Comment by ngarnier** [comment]
hey, Nicolas from the MJML team here! Don't hesitate if you have any question regarding integrating MJML, happy to help. 

Regarding your use case, you might be interested in creating an [MJML JSON structure](https://mjml.io/documentation/#using-mjml-in-json) (easy to manipulate) from blocks users drag and drop to then render the full template as responsive HTML.

**Comment by artf** [comment]
Thanks @ngarnier for reaching out to me, MJML team made a really great work. I've already started playing around with the framework and I hope to release soon the first release of the plugin :)

**Comment by witzig** [comment]
@artf, awesome! Just started poking around the codebase this evening thinking about giving this a shot myself (in case you weren't already on it). 

I'm thrilled to read this! Guess we all are. :)

**Comment by artf** [comment]
@witzig @ngarnier @HLFH 
The first release is out https://github.com/artf/grapesjs-mjml
At the moment, works only with few standard components from the MJML library but I think it's ok as a starting point.
Here you can find the [demo](http://grapesjs.com/demo-mjml.html)
