### ISSUE TITLE
Unable to open the index.html 

### ISSUE THREAD

**Issue by VCheque** [artf/grapesjs-preset-newsletter#35]
Hi all

After I execute **npm start** it shows

$ npm start

> grapesjs-preset-newsletter@0.2.17 start C:\Users\a233243\grapesjs-preset-newsletter
> cross-env WEBPACK_ENV=dev ./node_modules/.bin/webpack-dev-server --progress --colors & npm run build:css -- -w

 10% building modules 1/1 modules 0 active
Project is running at http://localhost:8080/
webpack output is served from /
Hash: bbf63f4da00946016442
Version: webpack 3.11.0
Time: 5037ms

But when I go to **http://localhost:8080//index.html** it shows just a blank page. What can I do?

**Comment by artf** [comment]
what about removing those `//` in `http://localhost:8080//index.html`
