### ISSUE TITLE
Emails not rendering well in clients

### ISSUE THREAD

**Issue by goulaheau** [artf/grapesjs-preset-newsletter#36]
Hi, 

I'm trying to use this library to create some emails and send them, so I use the combinaison of grapesjs + this preset and send the output of the command gjs-get-inlined-html. But when I open it in Outlook or Gmail, the email is very different. I even tried to copy the demo newsletter and the result was not satisfying.

Should I add something else than the ouput of the command gjs-get-inlined-html to get a well rendered email in all major clients ?

Thanks in advance.

**Comment by fahrirusliyadi** [comment]
I've got the same issue.

I'm using:
- grapesjs v0.14.21
- grapesjs-preset-newsletter v0.2.15
- Google Chrome Version 67.0.3396.99

Steps to reproduce:

1. Open https://grapesjs.com/demo-newsletter-editor.html.
1. Import the following template:

    ~~~html
    <table style="box-sizing: border-box; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; margin-bottom: 20px; height: 0px;" height="0">
        <tbody style="box-sizing: border-box;">
            <tr style="box-sizing: border-box;">
                <td style="box-sizing: border-box; background-color: rgb(255, 255, 255); overflow-x: hidden; overflow-y: hidden; border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; text-align: center;" bgcolor="rgb(255, 255, 255)" align="center">
                    foobar 
                </td>
            </tr>
        </tbody>
    </table>
    ~~~

1. Get html with inlined CSS with `editor.runCommand('gjs-get-inlined-html')` command. It will produce the following output:

    ~~~html
    <table height="0" class="c2665" style="box-sizing: border-box; min-height: 150px; padding-top: 5px; padding-right: 5px; padding-bottom: 5px; padding-left: 5px; margin-bottom: 20px; height: 0px;"><tbody style="box-sizing: border-box;"><tr style="box-sizing: border-box;"><td bgcolor="rgb(255, 255, 255)" align="center" style="box-sizing: border-box;">
                foobar 
            </td></tr></tbody></table>
    ~~~

    Notice the `<td>` tag does not have all of the styles.

**Comment by fahrirusliyadi** [comment]
After updating to grapesjs v0.14.23, it's working as expected.
