### ISSUE TITLE
Link element(or Link block) , I cant find how/where to set href 

### ISSUE THREAD

**Issue by shareefhiasat** [artf/grapesjs-preset-newsletter#39]
Hi @artf  can you please have a minute to look at this issue. 

**Problem** : i cant set the href for news letter preset

**Steps to reproduce**:
Please follow the steps:

1. go to the demo http://grapesjs.com/demo-newsletter-editor.html of newsletter preset.
2. try add link element block
3. click on it and try to set or change the link , ! just _dimension/Typography/Decorations_

Regards

**Comment by artf** [comment]
You can find them in settings panel
![schermata 2018-05-26 alle 14 58 37](https://user-images.githubusercontent.com/11614725/40576367-560424c8-60f5-11e8-8528-835b10b9b9f4.png)
