### ISSUE TITLE
Get export with inline css

### ISSUE THREAD

**Issue by niagi** [artf/grapesjs-preset-newsletter#4]
Hi,
So I am trying to get the html with inline css so save to db. 

(using this command to get the data)
```
{
         id: "save-template",
         run: function(editor, senderBtn) {
                 // Deactivate button
                 senderBtn.set("active", false);
                 var html = editor.getHtml();
                 var css = editor.getCss();
                 var exportHtml = // something to get the inline css                     
                 mail.saveTemplate(html, css); // my save function
          },
          stop: function(editor, sender) {
                  // do something
                 }
         }
```

Since there's not that much documentation I am not really sure how to access this.
Any help would be appreciated :)

**Comment by niagi** [comment]
Managed to fix it,
looked through your demo file and saw the test-send function where you use it :)

**Comment by artf** [comment]
well done @niagi, you can actually call it in this way:
```js
var html = editor.runCommand('gjs-get-inlined-html');
```

**Comment by w9009** [comment]
> well done @niagi, you can actually call it in this way:
> 
> ```js
> var html = editor.runCommand('gjs-get-inlined-html');
> ```

Cant get this command to work when using vite to build.
