### ISSUE TITLE
how to call the gjs-get-inlined-html command

### ISSUE THREAD

**Issue by JPPreusDev** [artf/grapesjs-preset-newsletter#44]
Please help me figure out how to call the gjs-get-inlined-html command.

**Comment by LKozakewycz** [comment]
```javascript
var editor = grapesjs.init({
// ...
});

console.log(editor.Commands.get('gjs-get-inlined-html'));
```

That works. My concern now is how I actually get the HTML. This returns an object.

**Comment by LKozakewycz** [comment]
Worked it out:

```javascript
var editor = grapesjs.init({
// ...
});

console.log(editor.Commands.get('gjs-get-inlined-html').run(editor));
```

**Comment by AnkitKachhadiya** [comment]
You can also do like this:

```
var editor = grapesjs.init({
// ...
});
console.log(editor.runCommand('gjs-get-inlined-html'));
```

**Comment by carboni-rob** [comment]
It's returning `undefined` for me. Any idea why?

**Comment by zolga** [comment]
I'm getting undefined as well, any update on this?

**Comment by chezhiane** [comment]
getting undefined as well any reasons ?

**Comment by yatide** [comment]
Same here

**Comment by artf** [comment]
`editor.runCommand('gjs-get-inlined-html')` works in the [demo](https://grapesjs.com/demo-newsletter-editor.html) (you can try it in dev console). Be sure to use the latest version

**Comment by Yannik-Slym** [comment]
Hello @artf 

I have the same issue but only at the initialization after the command work fine. 

/*! grapesjs - 0.16.12 */
/*! grapesjs-preset-newsletter - 0.2.20 */

```js
grapesjs.init({
   plugins: ['gjs-preset-newsletter'],
   pluginsOpts: {
      'gjs-preset-newsletter': {
   }
},
});

// Doesn't work
editor.runCommand('gjs-get-inlined-html')

editor.on('change:changesCount', e => {
    // Work after first edition
    editor.runCommand('gjs-get-inlined-html')
});
```

Thanks :)
