### ISSUE TITLE
[Bug]: "gjs-get-inlined-html" command missing from 0.2.19

### ISSUE THREAD

**Issue by carboni-rob** [artf/grapesjs-preset-newsletter#51]
`editor.Commands.has('gjs-get-inlined-html')` returns `false`.
`editor.Commands.has('gjs-open-import-template')` and `editor.Commands.has('gjs-toggle-images')` correctly return true.
As a consequence, it's currently impossible to get the inlined html to send.
`grapesjs 0.14.27`
`grapesjs-preset-newsletter 0.2.19`

**Comment by artf** [comment]
Probably in your settings, you have changed the `pfx` option and the command name was relying on that. Anyway, I just released https://github.com/artf/grapesjs-preset-newsletter/releases/tag/v0.2.20 with a fixed command name that can be changed via `cmdInlineHtml` option
