### ISSUE TITLE
Question: Combining blocks and style manager on a panel

### ISSUE THREAD

**Issue by niagi** [artf/grapesjs-preset-newsletter#6]
I am trying to build a custom "simple-edit panel" and I am trying to combine a few (custom) blocks on the panel and also some buttons.

First of all. I've tried to read the documentation (for the main project) but maybe I am missing something or its not there yet.. 

I have "removed" the class tree view and my idea is to take that spot and build a custom menu in its place. Not sure the best way to go about this. I did some tests first just filling the views-container panel but my guess is this is not the best way to do this.

Any help would be appreciated :)

**Comment by artf** [comment]
Yeah at the moment there are no helpers for UI panel management (I've started to work on this but switched to other tasks) so you have to "move" all stuff manually with js

**Comment by Sibbir7350** [comment]
@artf 
Any update on panel management ??

I want to remove all panel.. I want to use only canvas for editing and I will use custom button to add component
