### ISSUE TITLE
How to set tablet device as default

### ISSUE THREAD

**Issue by subhajeet2107** [artf/grapesjs-preset-newsletter#64]
I have tried DeviceManager, but i cant set Tablet Device as default it is always opening with Desktop in device buttons, how can i trigger Tablet mode on load ?

**Comment by AlessandroMagri** [comment]
Just after 

`editor  = grapesjs.init({ ... });`

You can insert 
`editor.setDevice('Tablet');`

**Comment by subhajeet2107** [comment]
Thanks, it is getting back to Desktop device for some reasons
