### ISSUE TITLE
Problems on Create Blocks Categories

### ISSUE THREAD

**Issue by rgcarrasqueira** [artf/grapesjs-preset-newsletter#7]
Hi Art!

I'm trying to make blocks under categories to organize the presentation to my users. I would like to set two categories:

1 - With default set of blocks
2 - An another with my own custom blocks.

I've tried:

```

var blockManager = editor.BlockManager;
    
    blockManager.add('name-block', {
        label: '{% trans "Nome" %}',
        content: '<p>{% templatetag openvariable %}name{% templatetag closevariable %}</p>',
        category: 'Campos',
        attributes: {
            title: '{% trans "Nome" %}',
            class: 'gjs-fonts gjs-custom-field'
        }
    });

editor.on('load', function() {
        //Insert loading code here
        blockManager.getAll().reset();
        
    });

```
But no effect at my view:
![screen shot 2017-07-14 at 21 17 16](https://user-images.githubusercontent.com/97540/28234760-da2c2da0-68d9-11e7-8806-631d57f49e7d.png)

I would like to do something like that:

![screen shot 2017-07-14 at 21 19 49](https://user-images.githubusercontent.com/97540/28234798-31256a18-68da-11e7-8cd8-5711bfab924c.png)

But on newsletter preset it is appearing not possible. Any clue on solve that?

Thanks a lot!

**Comment by artf** [comment]
Try to update grapesjs, if you paste, for instance, `editor.BlockManager.add('test-block',{category:'test cat', label: 'Label'})` inside the devtool, you'll see that it works as expected

**Comment by rgcarrasqueira** [comment]
Now it is working, but all to redefine a category for a button already setup at main.js?
