### ISSUE TITLE
[QUESTION]: Disable css media queries

### ISSUE THREAD

**Issue by genesysflow** [artf/grapesjs-preset-newsletter#70]
Hi,  is there a way too completely disable css media queries? Would be nice to just have the simple css no mater what device is set.
Thanks

**Comment by lajby95** [comment]
When you specify the deviceManager properties, put `widthMedia` with a very high arbitrary value:
`widthMedia: '20000px'`

Like this:
<pre>var editor  = grapesjs.init({
	deviceManager: {
		{
			name: 'Desktop',
			width: "900px",
			widthMedia: '20000px',
		}, {
			name: 'Mobile',
			width: '320px',
			widthMedia: '20000px',
		}
	},
	styleManager: {
		...
	},
	etc: {
		...
	}
})</pre>

This way, you will only get one media query of max-width: 20000px, so no matter how you resize the resulted html, it will look the same.

**Comment by osama-bp** [comment]
Anyone still looking for a fix, add `devicePreviewMode: 1` to your grapesjs init method.
