### ISSUE TITLE
gyp verb check python checking for Python executable "python2" in the PATH

### ISSUE THREAD

**Issue by eyeamkd** [artf/grapesjs-preset-newsletter#80]
Why is this repository still checking for Python2. Since there's no Python 2.7 in my system, the installation script throws a configurable error, and finally returns a "Build failed with error code :1 "

**Comment by artf** [comment]
Without any example of the log, I think it might be some dependency or directly an issue with your environment

**Comment by eyeamkd** [comment]
![grapes-error](https://user-images.githubusercontent.com/31094327/74035154-bca9ca00-49df-11ea-95cf-114a9abeaf9e.png)

This is the error that's showing up
